spring:
  application:
    name: Nexus
  sql:
    init:
      mode: always
  datasource:
    # DB가 닫혀도 메모리 데이터를 유지하도록 설정
    url: jdbc:mysql://nexus-db.c10skc0kg6a5.ap-northeast-2.rds.amazonaws.com:3306/nexus_db?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
    username: admin
    password: dhkdxmsxmswkdrn
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 처음 실행 시 테이블을 자동으로 만들어줍니다.
    properties:
      hibernate:
        format_sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.Nexus.domain
  configuration:
    map-underscore-to-camel-case: true