spring:
  application:
    name: Nexus
  sql:
    init:
      mode: always
  datasource:
    # DB가 닫혀도 메모리 데이터를 유지하도록 설정
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true # 웹에서 DB를 확인할 수 있게 콘솔 활성화
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.Nexus.domain
  configuration:
    map-underscore-to-camel-case: true